### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by paolo-binary** [foxfolio/foxfolio-website#1]
Hello,
I own the domain foxfolio.app so maybe you'd like to unlink it from your project. 
Thanks

**Comment by greimela** [comment]
Hey, thanks for the report.
I’ve checked all the places where custom domain names are configured and it looks like foxfolio.app isn’t configured anywhere.

What did I miss?

**Comment by paolo-binary** [comment]
Hi Andreas, here a screenshot
Thanks for the cooperation 🙂 

<img width="721" alt="Screenshot 2024-03-27 at 09 31 19" src="https://github.com/foxfolio/foxfolio.github.io/assets/60384146/871790a8-0e5c-419b-921a-a95803a562fb">

**Comment by greimela** [comment]
Ah, in the organization, thanks.
I've updated it!
